=== jtellnes/arkade5/src/Arkivverket.Arkade.Core.Tests/TestData/Siard/testuttrekk_med_blobs/content/schema0/table3/table3.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.bar.admin.ch/xmlns/siard/2/table.xsd" targetNamespace="http://www.bar.admin.ch/xmlns/siard/2/table.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.1">
	<!-- root element is the table element -->
	<xs:element name="table">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Root element of a table of the SIARD archive. A table consists of rows.</xs:documentation>
			</xs:annotation>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="row" type="recordType" />
			</xs:sequence>
			<xs:attribute name="version" type="versionType" use="required" />
		</xs:complexType>
	</xs:element>
	<!-- simple type for version number -->
	<xs:simpleType name="versionType">
		<xs:annotation>
			<xs:documentation>versionType is constrained to "2.1" for conformity with this XML schema</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse" />
			<xs:enumeration value="2.1" />
			<!--  to be extended later with
      <xs.enumeration value="2.2"/>
      etc. -->
		</xs:restriction>
	</xs:simpleType>
	<!-- complex type record -->
	<xs:complexType name="recordType">
		<xs:annotation />
		<xs:sequence>
			<xs:element name="c1" minOccurs="0" type="xs:integer" />
			<xs:element name="c2" minOccurs="0" type="xs:integer" />
			<xs:element name="c3" minOccurs="0" type="xs:string" />
			<xs:element name="c4" minOccurs="0" type="xs:string" />
			<xs:element name="c5" minOccurs="0" type="xs:string" />
			<xs:element name="c6" minOccurs="0" type="blobType" />
			<xs:element name="c7" minOccurs="0" type="xs:string" />
			<xs:element name="c8" minOccurs="0" type="xs:string" />
			<xs:element name="c9" minOccurs="0" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<!-- type for text large objects -->
	<xs:complexType name="clobType">
		<xs:annotation>
			<xs:documentation>a text large object stored separately (addressed by URI). The digest makes sure, the connection to the object is not completely lost. The length is in characters, not in bytes.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="file" type="xs:anyURI" />
				<xs:attribute name="length" type="xs:integer" />
				<xs:attribute name="digestType" type="digestTypeType" />
				<xs:attribute name="digest" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!-- type for binary large objects -->
	<xs:complexType name="blobType">
		<xs:annotation>
			<xs:documentation>a binary large object stored separately (addressed by URI). The digest makes sure, the connection to the external object is not completely lost. The length is in bytes.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:hexBinary">
				<xs:attribute name="file" type="xs:anyURI" />
				<xs:attribute name="length" type="xs:integer" />
				<xs:attribute name="digestType" type="digestTypeType" />
				<xs:attribute name="digest" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!--  type for message digest type -->
	<xs:simpleType name="digestTypeType">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse" />
			<xs:enumeration value="MD5" />
			<xs:enumeration value="SHA-1" />
			<xs:enumeration value="SHA-256" />
		</xs:restriction>
	</xs:simpleType>
	<!-- date type between 0001 and 9999 restricted to UTC -->
	<xs:simpleType name="dateType">
		<xs:restriction base="xs:date">
			<xs:minInclusive value="0001-01-01Z" />
			<xs:maxExclusive value="9999-12-31Z" />
			<xs:pattern value="\d{4}-\d{2}-\d{2}Z?" />
		</xs:restriction>
	</xs:simpleType>
	<!-- time type restricted to UTC -->
	<xs:simpleType name="timeType">
		<xs:restriction base="xs:time">
			<xs:pattern value="\d{2}:\d{2}:\d{2}(\.\d+)?Z?" />
		</xs:restriction>
	</xs:simpleType>
	<!-- dateTime type between 0001 and 9999 restricted to UTC -->
	<xs:simpleType name="dateTimeType">
		<xs:restriction base="xs:dateTime">
			<xs:minInclusive value="0001-01-01T00:00:00.000000000Z" />
			<xs:maxExclusive value="9999-12-31T23:59:59.9999999Z" />
			<xs:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z?" />
		</xs:restriction>
	</xs:simpleType>
	<!--Create time: 08.09.2020 09.47.54-->
	<!--Table schema0/table3 corresponds to the actual table or view objekt-->
</xs:schema>

=== jtellnes/arkade5/src/Arkivverket.Arkade.Core.Tests/TestData/Siard/testuttrekk_med_blobs/content/schema0/table3/table3.xml
<?xml version="1.0" encoding="utf-8"?>
<!--Create time: 08.09.2020 09.47.54-->
<!--Table schema0/table3 corresponds to the actual table objekt-->
<table xsi:schemaLocation="http://www.bar.admin.ch/xmlns/siard/2/table.xsd table3.xsd" version="2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.bar.admin.ch/xmlns/siard/2/table.xsd">
	<row>
		<c1>1</c1>
		<c2>1</c2>
		<c3>Dokument 1</c3>
		<c4>Rådet for trygg trafikk</c4>
		<c5>Merknad dokument 1</c5>
		<c6 file="seg0/rec1.bin" length="1922" digestType="MD5" digest="8AB663653CD42207F4F5C823569091F2" />
		<c7>Vedlikehold av Noark 5.txt</c7>
		<c8>TXT</c8>
		<c9>TXT-dokument</c9>
	</row>
	<row>
		<c1>2</c1>
		<c2>2</c2>
		<c3>Dokument 2</c3>
		<c5>Merknad dokument 2</c5>
		<c6 file="seg0/rec2.bin" length="2080" digestType="MD5" digest="0C93086B4A613768020C1DC1664B2DDB" />
		<c7>utvalg_k2000v01_addml_7.3.XML</c7>
		<c8>XML</c8>
		<c9>XML-dokument</c9>
	</row>
	<row>
		<c1>3</c1>
		<c2>3</c2>
		<c3>Dokument 3</c3>
		<c4>Brannstyret</c4>
		<c5>Merknad dokument 3</c5>
		<c6 file="seg0/rec3.bin" length="128690" digestType="MD5" digest="9DF645D0F94ED03F825BA3AC7D61D6CC" />
		<c7>1.pdf</c7>
		<c8>PDF</c8>
		<c9>PDF-dokument</c9>
	</row>
	<row>
		<c1>4</c1>
		<c2>4</c2>
		<c3>Dokument 4</c3>
		<c4>Teknisk utval</c4>
		<c5>Merknad dokument 4</c5>
		<c6 file="seg0/rec4.bin" length="84951" digestType="MD5" digest="2AEB2D3201F0F3C64E12B82E2DDDD822" />
		<c7>2.pdf</c7>
		<c8>PDF</c8>
		<c9>PDF-dokument</c9>
	</row>
	<row>
		<c1>5</c1>
		<c2>5</c2>
		<c3>Dokument 5</c3>
		<c4>Møter i vassforyningsnemnda</c4>
		<c5>Merknad dokument 5</c5>
		<c6 file="seg0/rec5.bin" length="85382" digestType="MD5" digest="BBA74A3539CE9101A1B83026FFF63901" />
		<c7>5.pdf</c7>
		<c8>PDF</c8>
		<c9>PDF-dokument</c9>
	</row>
	<row>
		<c1>6</c1>
		<c2>214</c2>
		<c3>Dokument </c3>
		<c4>Oppføring av branngarasje i Andeby</c4>
		<c5>Merknad dokument 6</c5>
		<c6 file="seg0/rec6.bin" length="44304" digestType="MD5" digest="A22A732974392C6E59CAEFD16FD9E92C" />
		<c7>Noark 5v3.1 a5 Eks Arkivuttrekk xml.docx</c7>
		<c8>DOCX</c8>
		<c9>Word 2003-dokument</c9>
	</row>
	<row>
		<c1>7</c1>
		<c2>259</c2>
		<c3>Dokument </c3>
		<c4>Branngarasje på Gåsehaugen</c4>
		<c5>Merknad dokument 7</c5>
		<c6 file="seg0/rec7.bin" length="377344" digestType="MD5" digest="BA83B778F77EF0B2E24F145D529F3BB1" />
		<c7>Noark-5v3.1_a2_Metadatakatalog _objektsortert.doc</c7>
		<c8>DOC</c8>
		<c9>Word-dokument</c9>
	</row>
	<row>
		<c1>8</c1>
		<c2>308</c2>
		<c3>Dokument </c3>
		<c4>Vegar - vedlikehald diverse papir</c4>
		<c5>Merknad dokument 8</c5>
		<c6 file="seg0/rec8.bin" length="37665" digestType="MD5" digest="A4DCFB414C6B4930E139EB9C63C2E08D" />
		<c7>Noark-5v3.1_a4_Eks_Virksomhetsspesifikke_metadata.</c7>
		<c8>DOCX</c8>
		<c9>Word-dokument</c9>
	</row>
	<row>
		<c1>9</c1>
		<c2>328</c2>
		<c3>Dokument </c3>
		<c4>Nye vegar med kommunalt sommarvedlikehald</c4>
		<c5>Merknad dokument 9</c5>
		<c6 file="seg0/rec9.bin" length="168659" digestType="MD5" digest="4BDB4DF79FBC66AAC4988A5546DE2F7E" />
		<c7>Samlet oversikt over krav i Noark5_egenerklæring_3</c7>
		<c8>XLSX</c8>
		<c9>Word-dokument</c9>
	</row>
	<!--Row count: 9-->
	<!--Finished at: 08.09.2020 09.47.54-->
</table>
